/**
 * Gesture Classifier Implementation for XIAO nRF52840
 *
 * TensorFlow Lite Micro inference for sEMG gesture recognition.
 *
 * Target: Seeed Studio XIAO nRF52840 (non-Sense)
 * MCU: nRF52840 (Cortex-M4F @ 64MHz)
 * RAM: 256KB
 *
 * IMPORTANT: This uses the M2 CNN-only model because:
 * - LSTM models require 398KB+ RAM (doesn't fit)
 * - CNN models need ~80-120KB (fits well)
 */

#include "gesture_classifier.h"
#include <Arduino.h>
#include <cmath>
#include <cstring>

// ============================================================================
// TensorFlow Lite Micro Integration
// ============================================================================

#ifdef TFLITE_MICRO_ENABLED

// TFLite Micro headers
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/micro/system_setup.h"
#include "tensorflow/lite/schema/schema_generated.h"

// Include the model data
// Generated by conversion scripts:
//   - convert_m1_compressed.py for Compressed M1 CNN+LSTM
//   - convert_model_xiao.py for M2 CNN-only
//
// Priority: Compressed M1 > M2 > M1 > Placeholder
#if __has_include("m1_compressed_model.h")
    #include "m1_compressed_model.h"
    #define MODEL_DATA g_m1_compressed_model
    #define MODEL_DATA_LEN g_m1_compressed_model_len
    #define MODEL_HAS_LSTM 1
#elif __has_include("m2_model.h")
    #include "m2_model.h"
    #define MODEL_DATA g_m2_model
    #define MODEL_DATA_LEN g_m2_model_len
    #define MODEL_HAS_LSTM 0
#elif __has_include("m1_model.h")
    #include "m1_model.h"
    #define MODEL_DATA g_model
    #define MODEL_DATA_LEN g_model_len
    #define MODEL_HAS_LSTM 1
#else
    // Placeholder - will be replaced with actual model
    #warning "No model header found! Using placeholder."
    alignas(16) const unsigned char g_placeholder_model[] = {0};
    const unsigned int g_placeholder_model_len = 0;
    #define MODEL_DATA g_placeholder_model
    #define MODEL_DATA_LEN g_placeholder_model_len
    #define MODEL_HAS_LSTM 0
#endif

// Tensor arena - statically allocated
// Size tuned for M2 CNN model on nRF52840
// Adjust based on actual model requirements
alignas(16) static uint8_t tensor_arena[TENSOR_ARENA_SIZE];

// TFLite objects
static const tflite::Model* model = nullptr;
static tflite::MicroInterpreter* interpreter = nullptr;
static TfLiteTensor* input_tensor = nullptr;
static TfLiteTensor* output_tensor = nullptr;

// Op resolver - add only the ops your model needs
// This saves significant flash space vs AllOpsResolver
// Size depends on model type:
//   - CNN-only (M2): 12 ops
//   - CNN+LSTM (M1/Compressed M1): 16 ops (includes LSTM ops)
#if MODEL_HAS_LSTM
static tflite::MicroMutableOpResolver<16> resolver;
#else
static tflite::MicroMutableOpResolver<12> resolver;
#endif

#endif // TFLITE_MICRO_ENABLED

// ============================================================================
// Reinhard Compression Parameters
// ============================================================================

static const float REINHARD_RANGE = 1.0f;
static const float REINHARD_MIDPOINT = 32.0f;

// ============================================================================
// GestureClassifier Implementation
// ============================================================================

GestureClassifier::GestureClassifier()
    : initialized_(false)
    , last_latency_ms_(0)
    , model_(nullptr)
    , interpreter_(nullptr)
    , tensor_arena_(tensor_arena)
    , input_tensor_(nullptr)
    , output_tensor_(nullptr)
{
}

GestureClassifier::~GestureClassifier() {
    // Static allocation - nothing to free
}

bool GestureClassifier::begin() {
#ifdef TFLITE_MICRO_ENABLED
    // Initialize TFLite Micro
    tflite::InitializeTarget();

    // Load the model
    model = tflite::GetModel(MODEL_DATA);
    if (model == nullptr) {
        Serial.println("ERROR: Failed to load model");
        return false;
    }

    // Verify schema version
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        Serial.printf("ERROR: Model schema v%d, expected v%d\n",
                      model->version(), TFLITE_SCHEMA_VERSION);
        return false;
    }

    // Add required operations
    // Common CNN ops
    resolver.AddConv2D();
    resolver.AddDepthwiseConv2D();
    resolver.AddReshape();
    resolver.AddSoftmax();
    resolver.AddFullyConnected();
    resolver.AddMul();
    resolver.AddAdd();
    resolver.AddMean();
    resolver.AddRelu();
    resolver.AddMaxPool2D();
    resolver.AddQuantize();
    resolver.AddDequantize();

#if MODEL_HAS_LSTM
    // LSTM-specific ops for Compressed M1 / M1 models
    resolver.AddUnidirectionalSequenceLSTM();
    resolver.AddTranspose();
    resolver.AddStridedSlice();
    resolver.AddPack();
#endif

    // Build interpreter
    static tflite::MicroInterpreter static_interpreter(
        model, resolver, tensor_arena, TENSOR_ARENA_SIZE);
    interpreter = &static_interpreter;

    // Allocate tensors
    TfLiteStatus allocate_status = interpreter->AllocateTensors();
    if (allocate_status != kTfLiteOk) {
        Serial.println("ERROR: AllocateTensors() failed");
        Serial.printf("Arena size: %d bytes\n", TENSOR_ARENA_SIZE);
        return false;
    }

    // Get input/output tensors
    input_tensor = interpreter->input(0);
    output_tensor = interpreter->output(0);

    // Store references
    model_ = (void*)model;
    interpreter_ = (void*)interpreter;
    input_tensor_ = (void*)input_tensor;
    output_tensor_ = (void*)output_tensor;

    // Print tensor info
    Serial.println("TFLite Micro initialized:");
    Serial.printf("  Arena used: %d / %d bytes\n",
                  interpreter->arena_used_bytes(), TENSOR_ARENA_SIZE);
    Serial.printf("  Input dims: [");
    for (int i = 0; i < input_tensor->dims->size; i++) {
        Serial.printf("%d", input_tensor->dims->data[i]);
        if (i < input_tensor->dims->size - 1) Serial.print(", ");
    }
    Serial.println("]");
    Serial.printf("  Output dims: [");
    for (int i = 0; i < output_tensor->dims->size; i++) {
        Serial.printf("%d", output_tensor->dims->data[i]);
        if (i < output_tensor->dims->size - 1) Serial.print(", ");
    }
    Serial.println("]");

    initialized_ = true;
    return true;

#else
    // Stub mode - TFLite not enabled
    Serial.println("TFLite Micro not enabled - using stub classifier");
    Serial.println("To enable: add -DTFLITE_MICRO_ENABLED to build_flags");
    initialized_ = true;
    return true;
#endif
}

int GestureClassifier::classify(const float* emg_data, float* confidences) {
    if (!initialized_) {
        return -1;
    }

    uint32_t start_time = millis();
    int predicted_class = -1;

#ifdef TFLITE_MICRO_ENABLED
    // Apply Reinhard compression to input
    float* input_data = input_tensor->data.f;
    int input_size = 1;
    for (int i = 0; i < input_tensor->dims->size; i++) {
        input_size *= input_tensor->dims->data[i];
    }

    // Copy and compress input
    for (int i = 0; i < input_size && i < EMG_CHANNELS * WINDOW_SAMPLES; i++) {
        float x = emg_data[i];
        float abs_x = fabsf(x);
        input_data[i] = REINHARD_RANGE * x / (REINHARD_MIDPOINT + abs_x);
    }

    // Run inference
    TfLiteStatus invoke_status = interpreter->Invoke();
    if (invoke_status != kTfLiteOk) {
        Serial.println("ERROR: Inference failed");
        return -1;
    }

    // Get output
    const float* output_data = output_tensor->data.f;
    predicted_class = postProcess(output_data, confidences);

#else
    // Stub mode - return random results for testing
    float max_conf = 0.0f;
    for (int i = 0; i < NUM_GESTURES; i++) {
        confidences[i] = (float)random(1000) / 1000.0f;
        if (confidences[i] > max_conf) {
            max_conf = confidences[i];
            predicted_class = i;
        }
    }
#endif

    last_latency_ms_ = millis() - start_time;
    return predicted_class;
}

void GestureClassifier::applyReinhardCompression(float* data, int size) {
    for (int i = 0; i < size; i++) {
        float x = data[i];
        float abs_x = fabsf(x);
        data[i] = REINHARD_RANGE * x / (REINHARD_MIDPOINT + abs_x);
    }
}

int GestureClassifier::postProcess(const float* logits, float* confidences) {
    // Apply softmax and find argmax

    // Find max for numerical stability
    float max_val = logits[0];
    for (int i = 1; i < NUM_GESTURES; i++) {
        if (logits[i] > max_val) {
            max_val = logits[i];
        }
    }

    // Compute softmax
    float sum_exp = 0.0f;
    for (int i = 0; i < NUM_GESTURES; i++) {
        confidences[i] = expf(logits[i] - max_val);
        sum_exp += confidences[i];
    }

    // Normalize and find best class
    int best_class = 0;
    float best_conf = 0.0f;
    for (int i = 0; i < NUM_GESTURES; i++) {
        confidences[i] /= sum_exp;
        if (confidences[i] > best_conf) {
            best_conf = confidences[i];
            best_class = i;
        }
    }

    return best_class;
}

// ============================================================================
// Memory Information
// ============================================================================

extern "C" char* sbrk(int incr);

int GestureClassifier::getFreeHeap() {
    char top;
    return &top - reinterpret_cast<char*>(sbrk(0));
}

void GestureClassifier::printMemoryInfo() {
    Serial.println("\n=== Memory Info ===");
    Serial.printf("Free heap: %d bytes\n", getFreeHeap());
    Serial.printf("Tensor arena: %d bytes\n", TENSOR_ARENA_SIZE);

#ifdef TFLITE_MICRO_ENABLED
    if (interpreter != nullptr) {
        Serial.printf("Arena used: %d bytes\n", interpreter->arena_used_bytes());
        Serial.printf("Arena free: %d bytes\n",
                      TENSOR_ARENA_SIZE - interpreter->arena_used_bytes());
    }
#endif
}
